### PR TITLE
Commandline options, second try

### PR DESCRIPTION
**Pull request by zabbius**
Hi, ported my PR to new main branch. Has one question. How to use `config` variable from `youtubeUnblock.c` in `mangle.c`?

### CODE REVIEW

**Comment by Waujito** [comment]
Hi! Thank you!

I think if you just declare this variable as non-static in config.h and define in youtubeUnblock .c everything will be fine.

**Comment by jelly8173** [comment]
Why not use something like `getopt`? Just curious

**Comment by zabbius** [comment]
> Why not use something like `getopt`? Just curious

Because I did not used C for many many years. Just forget everything =) 
You're right. if  `getopt` is available as simple as `printf` we should use it.

**Comment by jelly8173** [comment]
> if `getopt` is available as simple as `printf` we should use it.

Its part of libc, ubiquitous in a linux world and one of the standard options to choose from when it comes to parse some args

**Pull request merged**
