### PR TITLE
Enhance bypass strategies

### PR DESCRIPTION
**Pull request by Waujito**

### CODE REVIEW

**Comment by jelly8173** [comment]
Sorry, a bit busy rn can't deep dive enough. I think function name tcp4_payload_split is a bit ambigous, is it intentional to prevent DPI devs to analyze sources and make counter-measures? Cause in my head it tends to work like: "this function will split payload in tcp packet in parts", but its actually not

**Comment by Waujito** [comment]
tcp4_payload_split splits the raw packet payload to ip header, tcp header and tcp payload.
Added comments for better understanding of that code.

**Comment by jelly8173** [comment]
> tcp4_payload_split splits the raw packet payload to ip header, tcp header and tcp payload.

Yeah, it's ambiguous as there is "split" strategy. Maybe better using word like decompose or "unpack"?

**Comment by Waujito** [comment]
> > tcp4_payload_split splits the raw packet payload to ip header, tcp header and tcp payload.
> 
> Yeah, it's ambiguous as there is "split" strategy. Maybe better using word like decompose or "unpack"?

Yes, may be unpack is more complete description for it, but I won't rename the function on which the entire program relies.

**Pull request merged**
